### ISSUE TITLE
AI/consumption-main.py 의 데이터가 웹에 제대로 반영되지 않는 문제

### ISSUE THREAD

**Issue by 4923** [KPMG-Fineapple/fineapple#26]
### 상황 공유
> 경로 다 바꿔봐도 그래프에 변화가 없고 터미널에서만 에러가 찍히길래 더미 데이터로 바꾸고, 임의로 값 변경해봤는데 그래프에 반영이 안 됨
> #20 이슈 제목과 관계 없어진 내용이라 새 이슈 생성

---
### log

<details>
<summary>시도해본 내용 기록</summary>

#### 1. python AI/consumption_main.py 실행시 출력값 문제없이 나오는 것 확인
<img width="1421" alt="스크린샷 2022-02-18 00 59 18" src="https://user-images.githubusercontent.com/60145951/154565856-f20f2b48-45ed-447e-a0c1-671a5c4ab002.png">

#### 2. 그런데도 같은 에러 발생: `Unexpected end of JSON input`
<img width="1789" alt="Unexpected_end_of_JSON_input" src="https://user-images.githubusercontent.com/60145951/154565286-66238bfa-c6d7-4221-880f-38d7add7bdbe.png">

#### 3. `BE/src/consumption/consumption.service.ts` 에서 파일명이 잘못 적힌것 확인 -> 변경
```ts
    # line no.9
    const process = spawnSync('python3', ['../AI/consumption-model.py']);
```
#### 4. 백엔드 파일 만지는것보다 파일명 변경하는게 낫겠어서 `consumption-model.py` 로 파일명 변경
- 원래 파일명 : `consumption_model.py`

#### 5. 이제 이런 에러가 발생함
<img width="1388" alt="스크린샷 2022-02-18 01 12 22" src="https://user-images.githubusercontent.com/60145951/154566128-ef22988f-f4fe-44e0-8d7b-bb645c90f308.png">

#### 6. 영문을 모르겠어서 consumption 값을 원래 더미데이터로 변경했는데 여전히 동일 에러 발생
<img width="1322" alt="스크린샷 2022-02-18 05 37 49" src="https://user-images.githubusercontent.com/60145951/154566721-7cedaf88-30b0-4e19-881f-686300876c41.png">

#### 7. 로드에 문제가 있는건지 확인해보려고 내부 값 하나씩 변경해봤는데 그래프에 변화가 없음 (!?)
시도한 값
- `[100, 100, 100, ... ]`
- `[i for i in range (100, 1000)]` -> [100, 101, 102 ... 999, 1000] 와 같음

#### 8. `BE/src/consumption/consumption.service.ts` 에서 파일 실행 경로가 `../AI/~` 이렇게 되어있어서 데이터 로드 경로를 변경해봄 -> 출력에 문제 없음
- `AI/data/~` -> `../AI/data/~`

|변경 전|변경 후|
|:-:|:-:|
|![전](https://user-images.githubusercontent.com/60145951/154571149-06a19673-918a-4bc7-b460-eae8aa0c02ca.png) | ![후](https://user-images.githubusercontent.com/60145951/154571207-bba0552c-e836-4821-8132-6569af91fb40.png)|

</details>

---
### 에러코드

```
[Nest] 39136  - 2022. 02. 18. 오전 5:28:56 VERBOSE [PowerGenerationController] address: hihi trying to get power generation
[Nest] 39136  - 2022. 02. 18. 오전 5:28:56 VERBOSE [ConsumptionController] address: hihi trying to get consumption
[Nest] 39136  - 2022. 02. 18. 오전 5:28:56   ERROR [ExceptionsHandler] Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at ConsumptionService.getConsumption (/Users/a4923/Desktop/repositories/fork_fineapple_ai/BE/src/consumption/consumption.service.ts:10:25)
    at ConsumptionController.getConsumption (/Users/a4923/Desktop/repositories/fork_fineapple_ai/BE/src/consumption/consumption.controller.ts:12:50)
    at /Users/a4923/Desktop/repositories/fork_fineapple_ai/BE/node_modules/@nestjs/core/router/router-execution-context.js:38:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /Users/a4923/Desktop/repositories/fork_fineapple_ai/BE/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at /Users/a4923/Desktop/repositories/fork_fineapple_ai/BE/node_modules/@nestjs/core/router/router-proxy.js:9:17
```

### 질문 @NEM-NE 
1. 에러코드에서 `at JSON.parse (<anonymous>)` 의 <annonymous> 부분이 제대로 된 값이 맞을까?
2. 그리고 더미값에 정수만 넣어줬던데 혹시 소수점 자릿수 제한된게 있어? 내 출력값이 대충 `6.12015962600708` 이런식으로 나와서 반올림해줘야할까 싶어서
3. 네 로컬에서 원래 더미로 넣어줬던 값 입력했을때 제대로 작동되고 있는지 + 또 더미값 변화시켰을때 그에따라 결과가 변화하는지 한번 확인부탁해! 

일단 테스트해보라고 모델이 예측한 값 남겨둘게
<details>
<summary>AI/consumption-main.py 실행 결과</summary>

```
{
    "current": 
    [{"date": "2021.1", "value": [17.9, 11.5, 15.1, 14.8, 15.8, 14.5, 16.3, 10.0, 10.6, 16.2, 14.5, 13.4, 11.5, 19.0, 15.0, 12.0, 15.4, 14.1, 16.7, 12.1, 17.3, 15.1, 18.0, 17.3, 11.4, 16.3, 12.1, 12.7, 11.7, 20.7, 20.3, 16.5]}, {"date": "2021.2", "value": [13.5, 14.9, 13.6, 12.4, 14.7, 14.2, 19.6, 15.5, 19.8, 8.9, 5.2, 7.9, 13.2, 17.2, 17.8, 14.6, 13.7, 13.2, 14.7, 13.4, 15.2, 15.5, 14.1, 12.0, 12.9, 13.6, 16.0, 12.7]}, {"date": "2021.3", "value": [18.0, 13.5, 12.7, 11.8, 12.1, 15.3, 12.4, 13.4, 5.2, 8.3, 15.0, 7.6, 16.3, 9.7, 16.5, 18.4, 11.9, 14.9, 15.2, 11.5, 16.9, 13.7, 14.8, 14.8, 10.9, 16.8, 13.8, 12.7, 11.9, 10.8, 13.3]}, {"date": "2021.4", "value": [15.2, 15.8, 16.2, 12.5, 16.7, 11.6, 13.1, 14.0, 16.6, 13.5, 12.6, 13.4, 12.6, 10.8, 15.1, 11.0, 10.9, 14.8, 11.1, 11.1, 10.4, 12.7, 14.1, 9.1, 15.0, 14.7, 9.7, 15.0, 13.7, 16.3]}, {"date": "2021.5", "value": [14.0, 17.1, 11.6, 13.0, 11.2, 13.2, 12.2, 17.7, 11.4, 11.8, 10.8, 15.4, 14.4, 14.6, 20.8, 14.9, 12.5, 11.9, 13.7, 8.6, 16.4, 13.1, 11.6, 14.0, 13.7, 10.8, 16.6, 11.1, 15.4, 9.6, 15.0]}, {"date": "2021.6", "value": [12.2, 11.1, 16.1, 10.3, 9.6, 9.6, 14.2, 13.3, 14.1, 15.9, 17.2, 16.0, 17.6, 17.4, 15.3, 15.4, 12.5, 16.2, 14.4, 17.0, 17.6, 14.5, 14.0, 15.1, 15.1, 15.8, 16.2, 14.2, 13.5, 15.8]}, {"date": "2021.7", "value": [15.9, 18.7, 16.3, 14.5, 14.6, 15.2, 16.4, 13.6, 15.6, 15.0, 20.6, 20.9, 17.7, 19.2, 13.0, 19.1, 24.8, 21.8, 27.1, 18.7, 24.0, 23.3, 21.2, 25.3, 21.8, 24.7, 20.0, 20.5, 19.3, 15.0, 18.9]}, {"date": "2021.8", "value": [18.6, 32.7, 18.3, 24.6, 21.6, 15.5, 21.1, 13.6, 19.2, 15.3, 10.1, 13.8, 17.9, 21.0, 15.9, 17.9, 13.0, 19.5, 14.2, 20.5, 13.9, 12.9, 14.1, 16.2, 13.9, 13.8, 12.9, 14.4, 18.8, 16.6, 12.6]}, {"date": "2021.9", "value": [9.1, 19.5, 14.9, 16.8, 18.4, 20.4, 16.9, 14.4, 12.0, 21.4, 14.1, 20.3, 15.0, 18.7, 13.6, 19.3, 10.0, 7.4, 13.1, 12.7, 20.1, 10.8, 9.7, 14.9, 3.6, 25.6, 11.3, 14.3, 15.3, 12.1]}, {"date": "2021.10", "value": [13.4, 13.8, 15.7, 16.4, 14.7, 16.5, 14.4, 13.7, 17.4, 13.8, 15.1, 18.0, 15.1, 13.8, 17.3, 12.4, 15.6, 16.5, 17.4, 16.3, 13.8, 22.1, 14.7, 13.4, 15.2, 18.4, 16.7, 14.5, 15.9, 16.0, 16.9]}, {"date": "2021.11", "value": [13.2, 17.9, 19.6, 14.6, 14.5, 19.0, 17.0, 21.4, 13.0, 19.2, 12.0, 13.7, 14.1, 15.3, 16.9, 18.2, 18.6, 20.5, 15.5, 13.7, 15.9, 14.4, 15.0, 13.2, 18.1, 14.4, 17.9, 15.5, 17.3, 19.8]}, {"date": "2021.12", "value": [13.4]}], 
    "predict"
    : [{"date": "2022.1", "value": [4.8508477210998535, 5.338593482971191, 3.208631992340088, 3.208631992340088, 3.208631992340088, 8.159523963928223, 5.03131628036499, 5.4700775146484375, 5.356387615203857, 5.990520000457764, 3.208631992340088, 4.622033596038818, 7.0179762840271, 2.8274035453796387, 5.826809406280518, 7.0179762840271, 4.622033596038818, 5.889653205871582, 7.0179762840271, 4.2750444412231445, 5.826809406280518, 5.338593482971191, 7.0179762840271, 5.880728721618652, 5.927676200866699, 5.835733890533447, 5.158657550811768, 5.981595516204834, 5.171510219573975, 5.356387615203857, 5.048951148986816, 5.927676200866699]}, {"date": "2022.2", "value": [5.338593482971191, 5.880728721618652, 5.936600685119629, 5.338593482971191, 5.990520000457764, 5.889653205871582, 5.338593482971191, 5.927676200866699, 5.990520000457764, 5.350121021270752, 5.350121021270752, 5.356387615203857, 5.158657550811768, 5.606781959533691, 5.826809406280518, 5.981595516204834, 5.981595516204834, 5.350121021270752, 7.0179762840271, 5.350121021270752, 5.615706443786621, 5.350121021270752, 5.606781959533691, 5.350121021270752, 7.0179762840271, 5.880728721618652, 5.606781959533691, 7.0179762840271]}, {"date": "2022.3", "value": [7.0179762840271, 5.826809406280518, 5.606781959533691, 7.758697032928467, 6.12015962600708, 5.284578800201416, 5.284578800201416, 7.0179762840271, 5.606781959533691, 5.981595516204834, 5.350121021270752, 5.981595516204834, 5.981595516204834, 5.880728721618652, 5.606781959533691, 5.606781959533691, 7.0179762840271, 5.606781959533691, 7.0179762840271, 5.285438060760498, 5.350121021270752, 5.981595516204834, 5.284578800201416, 5.927676200866699, 6.12015962600708, 5.981595516204834, 7.0179762840271, 5.284578800201416, 5.284578800201416, 7.97271203994751, 7.97271203994751]}, {"date": "2022.4", "value": [5.284578800201416, 8.159523963928223, 7.0179762840271, 5.284578800201416, 5.284578800201416, 5.350121021270752, 6.259929180145264, 7.0179762840271, 5.602623462677002, 6.019292831420898, 7.0179762840271, 5.367158889770508, 5.620521068572998, 5.619661808013916, 5.939034461975098, 7.656301498413086, 7.021239280700684, 6.559200763702393, 7.021239280700684, 7.656301498413086, 5.619661808013916, 6.305368900299072, 6.008334636688232, 5.685203552246094, 7.270394325256348, 5.606781959533691, 5.685203552246094, 7.656301498413086, 7.800683498382568, 7.884151935577393]}, {"date": "2022.5", "value": [7.021239280700684, 5.734760761260986, 6.305368900299072, 7.884151935577393, 7.021239280700684, 7.884151935577393, 7.884151935577393, 7.884151935577393, 7.021239280700684, 6.262166500091553, 1.2253707647323608, 0.978126049041748, 3.1894137859344482, 9.033586502075195, 10.457730293273926, 3.1029183864593506, 7.871805667877197, 6.262166500091553, 8.419929504394531, 5.344559669494629, 1.636714220046997, 23.89624786376953, 5.185783863067627, 9.033586502075195, 5.002988815307617, 1.1211844682693481, 1.636714220046997, 3.8202579021453857, 4.595468997955322, 8.419929504394531, 10.214062690734863]}, {"date": "2022.6", "value": [10.457730293273926, 8.348807334899902, 8.348807334899902, 7.498245716094971, 5.939034461975098, 2.7491490840911865, 7.372790813446045, 7.021239280700684, 6.251577854156494, 7.021239280700684, 8.419929504394531, 7.021239280700684, 7.372790813446045, 5.345028400421143, 7.656301498413086, 6.251577854156494, 7.758697032928467, 5.804969787597656, 7.372790813446045, 7.270394325256348, 7.0179762840271, 7.758697032928467, 5.345028400421143, 5.631412029266357, 7.270394325256348, 2.7491490840911865, 5.826809406280518, 5.024023532867432, 6.019292831420898, 5.367158889770508]}, {"date": "2022.7", "value": [5.367158889770508, 5.685203552246094, 5.620521068572998, 5.620521068572998, 6.008334636688232, 5.367158889770508, 5.432701587677002, 5.36801815032959, 5.880728721618652, 7.0179762840271, 5.981595516204834, 7.0179762840271, 5.606781959533691, 7.0179762840271, 5.606781959533691, 5.880728721618652, 5.367158889770508, 5.367158889770508, 5.432701587677002, 5.356387615203857, 5.36801815032959, 5.880728721618652, 5.36801815032959, 5.606781959533691, 7.0179762840271, 5.432701587677002, 5.880728721618652, 5.615706443786621, 5.606781959533691, 5.356387615203857, 5.889653205871582]}, {"date": "2022.8", "value": [5.936600685119629, 5.981595516204834, 5.880728721618652, 5.606781959533691, 5.367158889770508, 5.927676200866699, 5.889653205871582, 5.432701587677002, 5.981595516204834, 5.826809406280518, 5.880728721618652, 5.889653205871582, 5.826809406280518, 5.981595516204834, 5.835733890533447, 5.615706443786621, 5.880728721618652, 7.0179762840271, 5.835733890533447, 5.285438060760498, 5.606781959533691, 5.826809406280518, 5.606781959533691, 5.927676200866699, 5.880728721618652, 5.606781959533691, 5.615706443786621, 5.285438060760498, 7.0179762840271, 5.835733890533447, 5.826809406280518]}, {"date": "2022.9", "value": [7.0179762840271, 7.0179762840271, 5.835733890533447, 5.285438060760498, 5.835733890533447, 5.285438060760498, 5.284578800201416, 5.284578800201416, 5.285438060760498, 5.284578800201416, 5.615706443786621, 5.285438060760498, 5.284578800201416, 5.284578800201416, 5.285438060760498, 5.990520000457764, 5.889653205871582, 5.615706443786621, 5.350121021270752, 5.284578800201416, 5.889653205871582, 7.0179762840271, 5.350121021270752, 5.835733890533447, 5.826809406280518, 5.159516334533691, 5.835733890533447, 5.889653205871582, 5.158657550811768, 5.285438060760498]}, {"date": "2022.10", "value": [5.889653205871582, 5.350121021270752, 5.615706443786621, 5.285438060760498, 7.0179762840271, 7.0179762840271, 5.338593482971191, 5.158657550811768, 5.4700775146484375, 5.338593482971191, 4.317345142364502, 7.0179762840271, 5.171510219573975, 5.835733890533447, 4.516676425933838, 5.386273384094238, 5.4700775146484375, 5.927676200866699, 7.0179762840271]}, {"date": "2022.11", "value": []}, {"date": "2022.12", "value": []}]
}
```

</details>

_Originally posted by @4923 in https://github.com/KPMG-Fineapple/fineapple/issues/20#issuecomment-1043454479_

**Comment by 4923** [comment]
JSON 형식에 맞지 않으면 발생한다던데 🤔 뭐가문제일까...
- https://jthcast.dev/posts/2021-04-21-error-report/

**Comment by NEM-NE** [comment]
> 1. 에러코드에서 at JSON.parse (<anonymous>) 의 부분이 제대로 된 값이 맞을까?

=> 예전에도 해봤고 방금도 해봤는데 더미 데이터 자체는 잘 넘어갔어(누나가 올린 예시는 예측값 일부가 비어있어서 TypeError: Reduce of empty array with no initial value 에러가 떴는데 이거는 예외처리만 하면됨.)
그리고 데이터를 뜯어봤을 때 아무값도 안오더라고 빈 값으로 오기 때문에 Unexpected end of JSON input 에러가 발생하는 거야

> 2. 그리고 더미값에 정수만 넣어줬던데 혹시 소수점 자릿수 제한된게 있어? 내 출력값이 대충 6.12015962600708 이런식으로 나와서 반올림해줘야할까 싶어서

=> 방금 테스트 해본결과 그래도 잘받아!

> 3. 네 로컬에서 원래 더미로 넣어줬던 값 입력했을때 제대로 작동되고 있는지 + 또 더미값 변화시켰을때 그에따라 결과가 변화하는지 한번 확인부탁해!

=> 제대로 동작 & 사진 첨부

<img width="737" alt="스크린샷 2022-02-18 오후 2 32 31" src="https://user-images.githubusercontent.com/55152516/154623659-944c4fc5-c74b-43fa-8b59-c0a4e0a7bfe6.png">

**Comment by NEM-NE** [comment]
일단은 필요한게 내 로컬 환경 뿐만 아니라 서버에서도 파이썬이 돌아가게는 해야하니깐 라이브러리 의존성 문제부터 해결해줄 수 있어?
아니면 오늘 중으로 줌켜서 같이 해결해도 되고

**Comment by 4923** [comment]
일단 오케잉 나 건우랑 세시에 잠깐 회의하기로해서 그거 마무리되면 잠깐 줌으로 보자
몇시 괜찮아?

**Comment by NEM-NE** [comment]
>백엔드 서버에서 '../AI/consumption-model.py' 이 경로를 찾아간 후에 파일을 실행하는거야?

=> 맞아맞아 내가 consumption_main.py로 수정할게

>일단 오케잉 나 건우랑 세시에 잠깐 회의하기로해서 그거 마무리되면 잠깐 줌으로 보자 몇시 괜찮아?

이거는 오래 걸릴 거 같으니 끝나고 바로 하자 ㅋㅋㅋ

**Comment by 4923** [comment]
> => 맞아맞아 내가 consumption_main.py로 수정할게
=> 앗 아냐! 파일명 내쪽에서 수정했어!! 발전량 모델이 구분자 `-` 로 되어있어서 그냥 통일할겸

> 이거는 오래 걸릴 거 같으니 끝나고 바로 하자 ㅋㅋㅋ
=> 좋아 ㅋㅋㅋ 끝나면 나 점심만 먹고 슬랙 줄게!

**Comment by 4923** [comment]
04de562bce065ae9b029bbea9b3a85dffb2e0038 경로 수정하여 해결!
